"""add_user_theme

Revision ID: a2ed5283eeed
Revises: c7c4a9735a31
Create Date: 2026-02-04 02:49:52.557791+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ed5283eeed'
down_revision: Union[str, None] = 'c7c4a9735a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme', sa.String(length=10), server_default='light', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database from this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###
